### ISSUE TITLE
"Config file is not found"

### ISSUE THREAD

**Issue by havul** [jonmatthis/freemocap#35]
Hey there, Python beginner and stuck on an error when running; "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"

Google searches lead me to believe this is something to do with folder structure but not sure how to fix in practice. Any help would be appreciated!

[Log.txt](https://github.com/jonmatthis/freemocap/files/6872905/Log.txt)

**Comment by aaroncherian** [comment]
Hey! So, are you doing anything related to DeepLabCut (DLC) (e.g. object tracking, like tracking the juggling balls in Jon's video)? The config file it's looking for in this case is the config file for DLC. if you're not using DLC and you're just trying to do a quick video of yourself, instead of using the command `fmc.RunMe( )`, try
`fmc.RunMe(useDLC = False)`
so it won't look for anything DeepLabCut related.

**Comment by havul** [comment]
Perfectly solves the problem. Onto experimenting further with the program 👍
