### ISSUE TITLE
Is CUDA a necessary prerequisite?

### ISSUE THREAD

**Issue by vulkone** [jonmatthis/freemocap#36]
I have an AMD GPU so no CUDA but could I run it CPU only ?

**Comment by abitrolly** [comment]
@vulkone I am interested to know this too. AMD had some acceleration libs as well. So have you tried running it, and what error have you got?

**Comment by aaroncherian** [comment]
For right now, with openpose being our main method of body tracking, CUDA is a necessary prerequisite to the GPU version at least - OpenPose does have a CPU option, although I haven't tried to get it working with the pipeline yet, so that might take some finagling. 

We are hoping to get MediaPipe up and running soon as an alternate method of body tracking, and according to MediaPipe's documentation at the least, it seems as if they don't require CUDA for processing. We'll hopefully have more to say on that front in the coming weeks.
